### ISSUE TITLE
multiple responsibilities for a function

### ISSUE THREAD

**Issue by trangntt-016** [irenejoeunpark/ssgApplication#1]
I believe read, process, write files are different responsibilities and maybe you can try splitting them so that it'll be easier to read and debug 
`public static void main(String[] args) {

        String txtFileName = fileNameReader(args);

        String srcFile = "sources\\Sherlock-Holmes-Selected-Stories\\" + txtFileName;
        try {
            BufferedReader reader = new BufferedReader(new InputStreamReader(new FileInputStream(srcFile),"UTF-8"));
            String aLine;

            String fileName = txtFileName.split("\\.")[0];
            String htmlFileName = "dist/" + fileName + ".html";

            String beginParagraph = "<p>";
            String endPragraph = "</p>";

            String htmlFormB = "<!doctype html>\r\n"
                    + "<html lang=\"en\">\r\n"
                    + "<head>\r\n"
                    + "  <meta charset=\"utf-8\">\r\n"
                    + "  <title>"
                    + fileName
                    + "</title>\r\n"
                    + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
                    + "</head>\r\n"
                    + "<body>\r\n"
                    + "";

            String htmlFormE = "</body>\r\n"
                    + "</html>\r\n"
                    + "";

            new File("dist").mkdir();

            BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(htmlFileName),"UTF-8"));

            writer.write(htmlFormB);
            aLine = reader.readLine();
            writer.write("<h1>"+aLine + "</h1>");

            writer.write(beginParagraph);
            while((aLine = reader.readLine()) != null) {
                aLine = aLine.trim();
                if(aLine.length() == 0) {
                    writer.write(endPragraph);
                    writer.newLine();
                    writer.write(beginParagraph);
                }
                writer.write(aLine);
            }
            writer.write(endPragraph);
            writer.write(htmlFormE);
            writer.close();

        }catch(IOException e) {
            e.printStackTrace();
        }
    }`

**Comment by irenejoeunpark** [comment]
I created helper functions to clear out the code
